language: r
r:
  - release
cache: packages
latex: false
sudo: false

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

#r_packages:
#  - covr

#after_success:
#  - Rscript -e "library(covr); codecov()"
